### ISSUE TITLE
Freezing / Crashing in regulated apps

### ISSUE THREAD

**Issue by robertosw** [vishal2376/scroll-block#11]
**Describe the bug**
While YouTube is in foreground opened, a system popup appears after some random use time informing that Scroll Block is not responding. Options of the popup are "wait" and "kill".

When using either options, the popup will come back after some time.

Not yet tried in other apps

**Screenshots**
![20240629_180325](https://github.com/vishal2376/scroll-block/assets/47303535/f66753a9-97d9-4773-83c7-c19dd736a906)

**Smartphone:**
 - Device: Samsung Galaxy S21 Ultra
 - Android Version 14

**Additional context**
Battery optimisation is deactivated but there is no option for auto start in Samsungs Android UI

**Comment by vishal2376** [comment]
- Please make sure that you are using [latest version](https://github.com/vishal2376/scroll-block/releases/latest) of app

- It's very difficult to fix it without a **crash report**. You can send crash report (A pop-up dialog will be shown immediately after the app crashes,Tap "YES" to send report)

**Comment by robertosw** [comment]
I am on beta02. I dont get a crash report, probably because the app doesnt really crash just hangs for too long or it crashes in the background. I really only get whats shown in the screenshot. For me, nothing visibly happens after clicking either options. The popup just closes.

Is this pop up for the crash report from Android or your app?

**Comment by robertosw** [comment]
The popup telling me that scroll block froze also just happend in another app. YouTube was opened recently but at the time of the popup in the background

**Comment by robertosw** [comment]
Is there any way to access the logs of your app? I'd really like to help you with this

**Comment by vishal2376** [comment]
After a lot of research, I found out that ACRA (which detects crashes), doesn't support ANR (App not responding) errors

![image](https://github.com/vishal2376/scroll-block/assets/38159691/6b3ba85a-ca75-4b81-91cf-5825be484e26)

**Comment by vishal2376** [comment]
But i found out a way to detect ANR using ANR-Watchdog library. If you can reproduce the same crash, i can give you updated apk with ANR detection

**Comment by vishal2376** [comment]
Now, it will automatically crash the app if it detects App Not Responding. There will be different pop-up shown next time (I hope so..🫠) 

Here is update APK : [Scroll Block](https://drive.google.com/drive/folders/10RJN3tfGjU4Hb0_UyZolVbvEsUJteynY?usp=sharing)

**Comment by robertosw** [comment]
Thanks for the effort, I'll give an update as soon as VirusTotal is done and the app freezes again :D

**Comment by robertosw** [comment]
Could I use Androids built in stack tracing for this aswell? Or does this focus on system tracing and not on single apps?

**Comment by vishal2376** [comment]
> Could I use Androids built in stack tracing for this aswell? Or does this focus on system tracing and not on single apps?

You can whatever you want

**Comment by robertosw** [comment]
> Now, it will automatically crash the app if it detects App Not Responding. There will be different pop-up shown next time (I hope so..🫠)
> 
> Here is update APK : [Scroll Block](https://drive.google.com/drive/folders/10RJN3tfGjU4Hb0_UyZolVbvEsUJteynY?usp=sharing)

Nope, I still get the same popup :(

**Comment by vishal2376** [comment]
I don't know why it's happening only to you 🙃.

I got a lot of crash reports after first launch of app (2 out of them were Samsung S21 , Android 14),
After latest update (v1.0-beta02), the app is working fine on their devices

Here is reply of a Samsung user after update
![gmail](https://github.com/vishal2376/scroll-block/assets/38159691/aa4a16b7-6397-4599-a956-61fd094f39cc)

**Comment by robertosw** [comment]
Maybe I bricked something for my phone, you're probably right 🫠
