### ISSUE TITLE
Restricted Setting error on Android 13+ devices

### ISSUE THREAD

**Issue by selfxironCodes** [vishal2376/scroll-block#19]
Im using custom rom HyperOSLite (Xiaomi 11x)
And I don't have any perms to enable accessibility settings.
![Screenshot_2024-07-08-22-02-21-923_com android settings](https://github.com/vishal2376/scroll-block/assets/116839252/a21ed1bb-3371-4de3-b56e-f91687b0b1b9)
Let me know if there's some solution.

**Comment by vishal2376** [comment]
That's latest Android 13+ issue

You have to give permission in App info first.

App Info > 3 dots on Top-right corner > grant permission then try again

OR

You can see this solution of this error on YouTube

**Comment by umang-sinha** [comment]
In case you don't see the three dots in the top right corner, please refer to this comment: https://stackoverflow.com/a/74595442

**Comment by selfxironCodes** [comment]
Oh yea, it worked, thanks.
