### ISSUE TITLE
Scroll Block isn't responding

### ISSUE THREAD

**Issue by strawberry-soda** [vishal2376/scroll-block#22]
i can't count how many times it comes up in a day. whichever of the two i press, it doesn't stop the scroll block from working but the pop up is annoying.

screenshot:
![Screenshot_20240711-021216_Cromite~3](https://github.com/vishal2376/scroll-block/assets/155584345/77c19709-543f-4880-b2a8-3539efc8d28c)

crash log:

[crash-com-vishal2376-scrollblock-11_07-02-08-43_879.zip](https://github.com/user-attachments/files/16167480/crash-com-vishal2376-scrollblock-11_07-02-08-43_879.zip)

**Comment by vishal2376** [comment]
Thank you so much for providing the ANR crash report. (This is what i was looking for)

It happens due to strict Android 13+ security.
Now, I know the root cause of this error.You will not see this error in the **app launch** (Scroll Block v1.0).
